permalink: /:title.html
paginate: 8
paginate_path: "page:num"
# markdown: kramdown # GitHub Pages only supports kramdown as a Markdown processor. https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/
excerpt_separator: <!--more-->
